name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installCppcheck
      run: sudo apt install cppcheck --fix-missing
    - name: cppcheck
      run: cppcheck .
    - name: Build and packege
      run: dpkg-buildpackage -b -us -uc
