name: Build and Package

on: push
jobs:
  build:
    name: environment
    runs-on: ubuntu-latest

    steps:
    - name: read repo
      uses: actions/checkout@v2
      
    - name: installCppcheck
      run: sudo apt install cppcheck --fix-missing
    - name: 安装打包依赖
      run: sudo apt-get install debhelper qt5-qmake qtbase5-dev qttools5-dev-tools build-essential
    - name: cppcheck
      run: cppcheck .
    - name: qmake
      run: qmake
    - name: make
      run: make
    - name: Build and package
      run: dpkg-buildpackage -b -us -uc
